#'@description Gets rid of any NA entries and where exactmass is equal to zero.
#'
#' @param data standard format of a db table that is generated by the CompoundDb package. See inst/db_files/nativeDBfiles for examples. Gets rid of any NA entries and where exactmass is equal to zero.
#'



#the function
clean_data <- function(data) {
  # Clean data by removing entries with NA or where exactmass is 0.
  cleaned_data <- data %>%
    filter(!is.na(inchikey) & !is.na(inchi) &
             (!is.na(exactmass) & exactmass != 0) &
             !is.na(formula))
  #apply toupper function to inchiKey column.

  toupper(trimws(cleaned_data$inchikey))

  return(cleaned_data)
}
